from enum import Enum


class CaracterTypeEnum(Enum):
    CONTRATISTA = "contratista"
    ASIGNATARIO = "asignatario"
    PERMISIONARIO = "permisionario"
    USUARIO = "usuario"

class SiNoEnum(Enum):
    """Si o No Enum."""
    SI = "Sí"
    NO = "No"

class ProductEnum(Enum):
    """Key Vale of product"""
    PR03 = "PR03"
    PR07 = "PR07"
    PR08 = "PR08"
    PR09 = "PR09"
    PR10 = "PR10"
    PR11 = "PR11"
    PR12 = "PR12"
    PR13 = "PR13"
    PR14 = "PR14"
    PR15 = "PR15"
    PR16 = "PR16"
    PR17 = "PR17"
    PR18 = "PR18"
    PR19 = "PR19"

class SubProductEnum(Enum):
    """Key Vale of product"""
    SP1 = "SP1"
    SP2 = "SP2"
    SP3 = "SP3"
    SP4 = "SP4"
    SP5 = "SP5"
    SP6 = "SP6"
    SP7 = "SP7"
    SP8 = "SP8"
    SP9 = "SP9"
    SP10 = "SP10"
    SP11 = "SP11"
    SP12 = "SP12"
    SP13 = "SP13"
    SP14 = "SP14"
    SP15 = "SP15"
    SP16 = "SP16"
    SP17 = "SP17"
    SP18 = "SP18"
    SP19 = "SP19"
    SP20 = "SP20"
    SP21 = "SP21"
    SP22 = "SP22"
    SP23 = "SP23"
    SP24 = "SP24"
    SP25 = "SP25"
    SP26 = "SP26"
    SP27 = "SP27"
    SP28 = "SP28"
    SP29 = "SP29"
    SP30 = "SP30"
    SP31 = "SP31"
    SP32 = "SP32"
    SP33 = "SP33"
    SP34 = "SP34"
    SP35 = "SP35"
    SP36 = "SP36"
    SP37 = "SP37"
    SP38 = "SP38"
    SP39 = "SP39"
    SP40 = "SP40"
    SP41 = "SP41"
    SP42 = "SP42"
    SP43 = "SP43"
    SP44 = "SP44"
    SP45 = "SP45"
    SP46 = "SP46"
    SP47 = "SP74"
    SP48 = "SP84"

class PermisoEnum(Enum):
    """Permissions ENUM."""
    PER1 = "H/XXXXX/COM/AAAA"
    PER2 = "PL/XXXXX/EXP/ES/AAAA"
    PER3 = "PL/XXXXX/EXP/ES/MM/AAAA"
    PER4 = "PL/XXXXX/EXP/ESA/AAAA"
    PER5 = "PL/XXXXX/DIS/OM/AAAA"
    PER6 = "H/XXXXX/COM/AAAA"
    PER7 = "PL/XXXXX/TRA/OM/AAAA"
    PER8 = "PL/XXXXX/TRA/DUC/AAAA"
    PER9 = "PL/XXXXX/TRA/TM/AAAA"
    PER10 = "PQ/XXXXX/TRA/DUC/AAAA"
    PER11 = "PL/XXXXX/ALM/AAAA"
    PER12 = "PQ/XXXXX/ALM/AAAA"
    PER13 = "PL/XXXXX/ALM/AE/AAAA"
    PER14 = "PL/XXXXX/EXP/AE/AAAA"
    PER15 = "G/XXXXX/ALM/AAAA"
    PER16 = "P/XXXXX/ALM/AAAA"
    PER17 = "G/XXXXX/COM/GN/AAAA"
    PER18 = "G/XXXXX/COM/PETRO/AAAA"
    PER19 = "G/XXXXX/COM/CEE/AAAA"
    PER20 = "G/XXXXX/COMP/AAAA"
    PER21 = "G/XXXXX/DESC/AAAA"
    PER22 = "G/XXXXX/DIS/AAAA"
    PER23 = "G/XXXXX/DIS/OM/AAAA"
    PER24 = "G/XXXXX/EXP/ES/FE/AAAA"
    PER25 = "G/XXXXX/EXP/ES/MM/AAAA"
    PER26 = "G/XXXXX/GES/AAAA"
    PER27 = "G/XXXXX/LICUE/AAAA"
    PER28 = "G/XXXXX/REG/AAAA"
    PER29 = "G/XXXXX/TUP/AAAA"
    PER30 = "G/XXXXX/SAB/AAAA"
    PER31 = "G/XXXXX/TRA/OM/AAAA"
    PER32 = "P/XXXXX/TRA/TM/AAAA"
    PER33 = "P/XXXXX/TRA/OM/AAAA"
    PER34 = "G/XXXXX/TRA/AAAA"
    PER35 = "GN/XXXXX/P/TRA/DUC/AAAA"
    PER36 = "GN/XXXXX/TRA/DUC/AAAA"
    PER37 = "P/XXXXX/TRA/DUC/AAAA"
    PER38 = "P/XXXXX/P/TRA/DUC/AAAA"
    PER39 = "LP/XXXXX/DIST/AUT/AAAA"
    PER40 = "LP/XXXXX/DIST/PLA/AAAA"
    PER41 = "LP/XXXXX/DIST/DUC/AAAA"
    PER42 = "G/XXXXX/LPD/AAAA"
    PER43 = "LP/XXXXX/EXP/ES/AAAA"
    PER44 = "LP/XXXXX/EXP/AUT/AAAA"
    PER45 = "LP/XXXXX/COM/AAAA"
    PER46 = "LP/XXXXX/TRA/DUC/AAAA"
    PER47 = "G/XXXXX/LPT/AAAA"
    PER48 = "LP/XXXXX/TRA/AAAA"
    PER49 = "LP/XXXXX/ALM/AAAA"
    PER50 = "G/XXXXX/LPA/AAAA"
    PER51 = "LP/XXXXX/DIST/REP/AAAA"
    PER52 = "PL/XXXXX/EXP/ESA/MM/AAAA"
    PER53 = "PL/XXXXX/DIS/DUC/AAAA"
    PER54 = "SENER-REF-XXX-AAAA"
    PER55 = "SENER-TP-XXX-AAAA"
    PER56 = "SENER-CPG-XXX-AAAA"
